config/routes.rb
Rails.application.routes.draw do
  root :to => "curriculums#index_main"
  get 'curriculums/kishu_list' => "curriculums#kishu_list"
  get 'curriculums/mcquay' => "curriculums#mcquay"
  get 'curriculums/screw' => "curriculums#screw"
  get 'curriculums/mcquay/oh' => "curriculums#mcquayoh"
  get 'curriculums/mcquay/tenken' => "curriculums#mcquaytenken"
  devise_for :users
  resources :curriculums

end

app/models/curriculum.rb
class Curriculum < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/curriculums_controller.rb
class CurriculumsController < ApplicationController
  before_action :set_curriculum, only: [:show, :edit, :update, :destroy]

  # GET /curriculums
  # GET /curriculums.json
  def index_main
  end

  def kishu_list
  end

  def mcquay
  end

  def screw
  end

  def mcquayoh
    @curriculums = Curriculum.all
  end

  def mcquaytenken
  end

  def index
    @curriculums = Curriculum.all
  end

  # GET /curriculums/1
  # GET /curriculums/1.json
  def show
  end

  # GET /curriculums/new
  def new
    @curriculum = Curriculum.new
  end

  # GET /curriculums/1/edit
  def edit
  end

  # POST /curriculums
  # POST /curriculums.json
  def create
    @curriculum = Curriculum.new(curriculum_params)

    respond_to do |format|
      if @curriculum.save
        format.html { redirect_to @curriculum, notice: 'Curriculum was successfully created.' }
        format.json { render :show, status: :created, location: @curriculum }
      else
        format.html { render :new }
        format.json { render json: @curriculum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /curriculums/1
  # PATCH/PUT /curriculums/1.json
  def update
    respond_to do |format|
      if @curriculum.update(curriculum_params)
        format.html { redirect_to @curriculum, notice: 'Curriculum was successfully updated.' }
        format.json { render :show, status: :ok, location: @curriculum }
      else
        format.html { render :edit }
        format.json { render json: @curriculum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /curriculums/1
  # DELETE /curriculums/1.json
  def destroy
    @curriculum.destroy
    respond_to do |format|
      format.html { redirect_to curriculums_url, notice: 'Curriculum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curriculum
      @curriculum = Curriculum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curriculum_params
      params.require(:curriculum).permit(:title, :body, :image, :check, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/curriculums_helper.rb
module CurriculumsHelper
end

app/views/curriculums/_form.html.erb
<%= form_for(@curriculum) do |f| %>
  <% if @curriculum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@curriculum.errors.count, "error") %> prohibited this curriculum from being saved:</h2>

      <ul>
      <% @curriculum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_area :image %>
  </div>
  <div class="field">
    <%= f.label :check %><br>
    <%= f.text_area :check %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/curriculums/edit.html.erb
<h1>Editing Curriculum</h1>

<%= render 'form' %>

<%= link_to 'Show', @curriculum %> |
<%= link_to 'Back', curriculums_path %>

app/views/curriculums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Curriculums</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Image</th>
      <th>Check</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @curriculums.each do |curriculum| %>
      <tr>
        <td><%= curriculum.title %></td>
        <td><%= curriculum.body %></td>
        <td><%= curriculum.image %></td>
        <td><%= curriculum.check %></td>
        <td><%= curriculum.user_id %></td>
        <td><%= link_to 'Show', curriculum %></td>
        <td><%= link_to 'Edit', edit_curriculum_path(curriculum) %></td>
        <td><%= link_to 'Destroy', curriculum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curriculum', new_curriculum_path %>

app/views/curriculums/index_main.html.erb
熱源サービス支援ソフト<br><br>

<%= link_to '熱源サービス', '/curriculums/kishu_list' %><br>
<%= link_to '見積作成', '/curriculums' %><br>
<%= link_to '熱源 技術資料検索', '/curriculums' %><br>
<%= link_to '不具合事例', '/curriculums' %><br>

app/views/curriculums/kishu_list.html.erb
機種選択<br>

<%= link_to 'マッケイターボ', '/curriculums/mcquay' %><br>
<%= link_to 'スクリュー圧縮機', '/curriculums/screw' %><br>

app/views/curriculums/mcquay.html.erb
マッケイターボ<br>

<%= link_to 'OH作業手順', '/curriculums/mcquay/oh' %><br>
<%= link_to '点検方法', '/curriculums/mcquay/tenken' %><br>

app/views/curriculums/mcquayoh.html.erb
<p id="notice"><%= notice %></p>

<h1>マッケイターボOH作業手順</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Image</th>
      <th>Check</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @curriculums.each do |curriculum| %>
      <tr>
        <td><%= curriculum.title %></td>
        <td><%= curriculum.body %></td>
        <td><%= curriculum.image %></td>
        <td><%= curriculum.check %></td>
        <td><%= curriculum.user_id %></td>
        <td><%= link_to 'Show', curriculum %></td>
        <td><%= link_to 'Edit', edit_curriculum_path(curriculum) %></td>
        <td><%= link_to 'Destroy', curriculum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curriculum', new_curriculum_path %>

app/views/curriculums/mcquaytenken.html.erb
マッケイターボ点検方法

app/views/curriculums/new.html.erb
<h1>New Curriculum</h1>

<%= render 'form' %>

<%= link_to 'Back', curriculums_path %>

app/views/curriculums/screw.html.erb
スクリュー圧縮機

app/views/curriculums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @curriculum.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @curriculum.body %>
</p>

<p>
  <strong>Image:</strong>
  <%= @curriculum.image %>
</p>

<p>
  <strong>Check:</strong>
  <%= @curriculum.check %>
</p>

<p>
  <strong>User:</strong>
  <%= @curriculum.user_id %>
</p>

<%= link_to 'Edit', edit_curriculum_path(@curriculum) %> |
<%= link_to 'Back', curriculums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>